spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oaxt?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
#扫描classpath中mapper目录下的映射配置文件，针对于映射配置文件放到了resources目录下
  mapper-locations: classpath:/mybatis.mapper/*.xml
 #定义包别名，使用pojo时可以直接使用pojo的类型名称不用加包名
 # type-aliases-package:
